#!/bin/sh
rm -rf out
mkdir out
"$1" eliminate input.nova 8:9 x | sed -n "8p"
"$1" eliminate input.nova 11:9 x | sed -n "11p"
"$1" eliminate input.nova 17:9 x | sed -n "17p"
"$1" eliminate input.nova 14:9 x > out/input.nova
sed -n "14p" out/input.nova
echo "--- re-elaborated (quot-elim owes its well-definedness):"
"$1" elab out/input.nova
echo "--- and one the trial rejects:"
"$1" eliminate input.nova 23:11 x
rm -rf out
