#!/bin/sh
rm -rf out
mkdir out
"$1" eliminate input.nova 15:17 h > out/input.nova
sed -n "15p" out/input.nova
"$1" eliminate input.nova 24:9 x | sed -n "24p"
echo "--- and one the item has not cited its way into:"
"$1" eliminate input.nova 20:16 h
echo "--- re-elaborated:"
"$1" elab out/input.nova
rm -rf out
