#!/bin/sh
"$1" run surface-item "plus : ℕ → ℕ → ℕ
plus Z n = n
plus (S m) n = S (plus m n)"
"$1" run surface-item "data [a : 𝕌]
  B : U
  nil : El B
  ins : a → El B → El B"
"$1" run surface-item "decl : (n : ℕ)
  → ℕ"
