#!/bin/sh
rm -rf out
mkdir out
"$1" eliminate input.nova 10:19 n > out/input.nova
cat out/input.nova
echo "--- re-elaborated:"
"$1" elab out/input.nova
echo "--- and at an ARGUMENT position:"
"$1" eliminate input.nova 17:21 n > out/arg.nova
sed -n "17,18p" out/arg.nova
"$1" elab out/arg.nova
rm -rf out
