#!/bin/sh
rm -rf out
mkdir out
"$1" eliminate input.nova 11:9 x | sed -n "11,14p"
"$1" eliminate input.nova 16:9 x --deep | sed -n "16,22p"
"$1" eliminate input.nova 20:9 x | sed -n "20,22p"
"$1" eliminate input.nova 25:17 h > out/input.nova
sed -n "25p" out/input.nova
echo "--- re-elaborated (the switch closes by reflection, no obligation):"
"$1" elab out/input.nova
rm -rf out
